### PR TITLE
Merge auto generated ssh keys with template keys

### LINKED ISSUE #127: ssh-keys added twice in metadata request when instance template has already defined keys
```
com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Invalid value for field 'resource.metadata': '{  \"fingerprint\": \"Qi326XmAEto=\",  \"item\": [{    \"key\": \"ssh-keys\",    \"value\": \":ssh-rsa AAAAB3NzaC...'. Metadata has duplicate keys: ssh-keys",
    "reason" : "invalid"
  } ],
  "message" : "Invalid value for field 'resource.metadata': '{  \"fingerprint\": \"Qi326XmAEto=\",  \"item\": [{    \"key\": \"ssh-keys\",    \"value\": \":ssh-rsa AAAAB3NzaC...'. Metadata has duplicate keys: ssh-keys"
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1067)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at com.google.jenkins.plugins.computeengine.client.ComputeClient.insertInstance(ComputeClient.java:359)
	at com.google.jenkins.plugins.computeengine.InstanceConfiguration.provision(InstanceConfiguration.java:282)
	at com.google.jenkins.plugins.computeengine.ComputeEngineCloud.doProvision(ComputeEngineCloud.java:421)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:535)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:280)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:676)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at org.jenkinsci.plugins.ssegateway.Endpoint$SSEListenChannelFilter.doFilter(Endpoint.java:243)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.ResourceCacheControl.doFilter(ResourceCacheControl.java:134)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at io.jenkins.blueocean.auth.jwt.impl.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:61)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:99)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:135)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at jenkins.security.BasicHeaderProcessor.doFilter(BasicHeaderProcessor.java:93)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
	at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:90)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:82)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1701)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1668)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:502)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)
```

### PR DESCRIPTION
**Pull request by trik**
close #127

### CODE REVIEW

File: src/main/java/com/google/jenkins/plugins/computeengine/InstanceConfiguration.java [hunk 1]
```diff
@@ -55,14 +55,7 @@
...
 import java.io.PrintStream;
-import java.util.ArrayList;
-import java.util.Arrays;
-import java.util.Collections;
-import java.util.HashMap;
-import java.util.Iterator;
-import java.util.List;
-import java.util.Map;
-import java.util.Set;
+import java.util.*;
```
Comment (craigdbarber) [inline src/main/java/com/google/jenkins/plugins/computeengine/InstanceConfiguration.java]: For consistency, please switch this back to using qualified imports.

File: src/test/java/com/google/jenkins/plugins/computeengine/InstanceConfigurationTest.java [hunk 2]
```diff
@@ -23,21 +23,15 @@
...
-import com.google.api.services.compute.model.AcceleratorType;
-import com.google.api.services.compute.model.DiskType;
-import com.google.api.services.compute.model.Image;
-import com.google.api.services.compute.model.Instance;
-import com.google.api.services.compute.model.MachineType;
-import com.google.api.services.compute.model.Network;
-import com.google.api.services.compute.model.Region;
-import com.google.api.services.compute.model.Subnetwork;
-import com.google.api.services.compute.model.Zone;
+import com.google.api.services.compute.model.*;
```
Comment (craigdbarber) [inline src/test/java/com/google/jenkins/plugins/computeengine/InstanceConfigurationTest.java]: Switch these back as well please.

File: src/main/java/com/google/jenkins/plugins/computeengine/InstanceConfiguration.java [hunk 3]
```diff
@@ -355,11 +348,26 @@ public Instance instance() throws IOException {
...
           && instanceTemplate.getProperties().getMetadata().getItems() != null) {
+        List<Metadata.Items> instanceItems = instance.getMetadata().getItems();
         instanceTemplate
             .getProperties()
             .getMetadata()
             .getItems()
-            .forEach(instance.getMetadata().getItems()::add);
+            .forEach(
+                item -> {
+                  if (item.getKey().equals(SSH_METADATA_KEY)) {
```
Comment (craigdbarber) [inline src/main/java/com/google/jenkins/plugins/computeengine/InstanceConfiguration.java]: I wonder if this approach is useful for any existing items not just the SSH KEY. @ingwarsw what are your thoughts?

**Comment by craigdbarber** [comment]
Thanks very much for this contribution! Left a few notes in-line.

File: src/main/java/com/google/jenkins/plugins/computeengine/InstanceConfiguration.java [hunk 4]
```diff
@@ -355,11 +348,26 @@ public Instance instance() throws IOException {
...
+                    Metadata.Items existing =
+                        instanceItems.stream()
+                            .filter(m -> m.getKey().equals(item.getKey()))
+                            .findFirst()
+                            .orElse(null);
+                    if (existing != null) {
+                      existing.setValue(existing.getValue() + " " + item.getValue());
```
Comment (craigdbarber) [inline src/main/java/com/google/jenkins/plugins/computeengine/InstanceConfiguration.java]: Digging into the docs, it appears "\n" is the proper delimiter for multiple ssh keys: https://cloud.google.com/compute/docs/storing-retrieving-metadata

File: src/main/java/com/google/jenkins/plugins/computeengine/InstanceConfiguration.java (hunk 3 above)
Comment (stephenashank) [reply src/main/java/com/google/jenkins/plugins/computeengine/InstanceConfiguration.java]: Even if there is not a current additional use case, pulling it out into a helper method is a good idea for readability here. We almost do this with mergeMetadataItems in the ComputeClient, but it replaces rather than concatenating them

**Comment by craigdbarber** [comment]
Would also like to see an IT test added for this.

File: src/main/java/com/google/jenkins/plugins/computeengine/InstanceConfiguration.java (hunk 3 above)
Comment (trik) [reply src/main/java/com/google/jenkins/plugins/computeengine/InstanceConfiguration.java]: moved to an helper method. at the moment only ssh keys are merged, other metadata values are overwritten

**Comment by trik** [comment]
> Would also like to see an IT test added for this.

added an IT case in ComputeEngineCloudTemplateIT, an ssh connection is established using the key pair defined at template level. hope can be good

File: src/main/java/com/google/jenkins/plugins/computeengine/InstanceConfiguration.java [hunk 5]
```diff
@@ -156,6 +156,27 @@
...
   protected transient ComputeEngineCloud cloud;
 
+  public static List<Metadata.Items> mergeMetadataItems(
+      List<Metadata.Items> winner, List<Metadata.Items> loser) {
+    if (loser == null) {
+      loser = new ArrayList<Metadata.Items>();
+    }
+
+    // Remove any existing metadata that has the same key(s) as what we're trying to update/append
+    //
```
Comment (craigdbarber) [inline src/main/java/com/google/jenkins/plugins/computeengine/InstanceConfiguration.java]: Please remove extra comment line.

File: src/main/java/com/google/jenkins/plugins/computeengine/InstanceConfiguration.java [hunk 6]
```diff
@@ -156,6 +156,27 @@
   @Setter(AccessLevel.PROTECTED)
   protected transient ComputeEngineCloud cloud;
 
+  public static List<Metadata.Items> mergeMetadataItems(
```
Comment (craigdbarber) [inline src/main/java/com/google/jenkins/plugins/computeengine/InstanceConfiguration.java]: Looks like this is only used within this class, makes sense to restrict the scope to private, unless you want to make package scoped for unit testing purposes.

File: src/test/java/com/google/jenkins/plugins/computeengine/integration/ComputeEngineCloudTemplateIT.java [hunk 7]
```diff
@@ -131,4 +139,42 @@ public void testTemplateCloudIdLabelKeyAndValue() {
     assertEquals(
         cloud.getInstanceId(), instance.getLabels().get(ComputeEngineCloud.CLOUD_ID_LABEL_KEY));
   }
+
+  @Test
+  public void testConnectionWithTemplateSshKey() throws IOException, Exception {
+    assertTrue(connectToInstance());
+  }
+
+  private boolean connectToInstance() throws IOException, Exception {
```
Comment (craigdbarber) [inline src/test/java/com/google/jenkins/plugins/computeengine/integration/ComputeEngineCloudTemplateIT.java]: Since this is only called from the test method above, I think it makes sense to in-line it within the test method itself.

**Comment by craigdbarber** [comment]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running InjectedTest
[INFO] Running com.google.jenkins.plugins.computeengine.AcceleratorConfigurationTest
[INFO] Running com.google.jenkins.plugins.computeengine.CleanLostNodesWorkTest
[INFO] Running com.google.jenkins.plugins.computeengine.ComputeEngineCloudTest
[INFO] Running com.google.jenkins.plugins.computeengine.AutofilledNetworkConfigurationTest
[INFO] Running com.google.jenkins.plugins.computeengine.ConfigAsCodeTest
[INFO] Running com.google.jenkins.plugins.computeengine.GoogleKeyPairTest
[INFO] Running com.google.jenkins.plugins.computeengine.InstanceConfigurationTest
[INFO] Running com.google.jenkins.plugins.computeengine.SharedVpcNetworkConfigurationTest
[INFO] Running com.google.jenkins.plugins.computeengine.client.ClientFactoryTest
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.5 s - in com.google.jenkins.plugins.computeengine.SharedVpcNetworkConfigurationTest
[INFO] Running com.google.jenkins.plugins.computeengine.client.ComputeClientTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.61 s - in com.google.jenkins.plugins.computeengine.GoogleKeyPairTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.037 s - in com.google.jenkins.plugins.computeengine.client.ComputeClientTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 26.369 s - in com.google.jenkins.plugins.computeengine.client.ClientFactoryTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 28.001 s - in com.google.jenkins.plugins.computeengine.AcceleratorConfigurationTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 31.699 s - in com.google.jenkins.plugins.computeengine.ConfigAsCodeTest
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 32.844 s - in com.google.jenkins.plugins.computeengine.ComputeEngineCloudTest
[INFO] Tests run: 15, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 33.272 s - in InjectedTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 33.72 s - in com.google.jenkins.plugins.computeengine.CleanLostNodesWorkTest
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 34.775 s - in com.google.jenkins.plugins.computeengine.AutofilledNetworkConfigurationTest
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 56.765 s - in com.google.jenkins.plugins.computeengine.InstanceConfigurationTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 59, Failures: 0, Errors: 0, Skipped: 0

[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.google.jenkins.plugins.computeengine.integration.ComputeEngineCloudNoSnapshotCreatedIT
[INFO] Running com.google.jenkins.plugins.computeengine.integration.ComputeClientIT
[INFO] Running com.google.jenkins.plugins.computeengine.integration.ComputeEngineCloudOneShotInstanceIT
[INFO] Running com.google.jenkins.plugins.computeengine.integration.ComputeEngineCloudMultipeMatchingConfigurationsIT
[INFO] Running com.google.jenkins.plugins.computeengine.integration.ComputeEngineCloudTemplateNoGoogleLabelsIT
[INFO] Running com.google.jenkins.plugins.computeengine.integration.ConfigAsCodeTestIT
[INFO] Running com.google.jenkins.plugins.computeengine.integration.ComputeEngineCloudTemplateIT
[INFO] Running com.google.jenkins.plugins.computeengine.integration.ComputeEngineCloudSnapshotCreatedIT
[INFO] Running com.google.jenkins.plugins.computeengine.integration.ComputeEngineCloudWorkerFailedIT
[INFO] Running com.google.jenkins.plugins.computeengine.integration.ComputeEngineCloudNonStandardJavaIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 24.377 s - in com.google.jenkins.plugins.computeengine.integration.ComputeClientIT
[INFO] Running com.google.jenkins.plugins.computeengine.integration.ComputeEngineCloudMultipleLabelsIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 45.571 s - in com.google.jenkins.plugins.computeengine.integration.ComputeEngineCloudWorkerFailedIT
[INFO] Running com.google.jenkins.plugins.computeengine.integration.ComputeEngineCloud1WorkerCreatedFor2ExecutorsIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 101.314 s - in com.google.jenkins.plugins.computeengine.integration.ComputeEngineCloudMultipeMatchingConfigurationsIT
[INFO] Running com.google.jenkins.plugins.computeengine.integration.ComputeEngineCloudWorkerCreatedIT
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 77.204 s - in com.google.jenkins.plugins.computeengine.integration.ComputeEngineCloudMultipleLabelsIT
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 105.065 s - in com.google.jenkins.plugins.computeengine.integration.ComputeEngineCloudTemplateIT
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 105.521 s - in com.google.jenkins.plugins.computeengine.integration.ComputeEngineCloudNonStandardJavaIT
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 108.089 s - in com.google.jenkins.plugins.computeengine.integration.ComputeEngineCloudTemplateNoGoogleLabelsIT
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 116.728 s - in com.google.jenkins.plugins.computeengine.integration.ComputeEngineCloudNoSnapshotCreatedIT
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 81.947 s - in com.google.jenkins.plugins.computeengine.integration.ComputeEngineCloud1WorkerCreatedFor2ExecutorsIT
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 152.115 s - in com.google.jenkins.plugins.computeengine.integration.ComputeEngineCloudOneShotInstanceIT
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 181.178 s - in com.google.jenkins.plugins.computeengine.integration.ConfigAsCodeTestIT
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 83.272 s - in com.google.jenkins.plugins.computeengine.integration.ComputeEngineCloudWorkerCreatedIT
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 197.159 s - in com.google.jenkins.plugins.computeengine.integration.ComputeEngineCloudSnapshotCreatedIT
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 29, Failures: 0, Errors: 0, Skipped: 0
